sudo: required
services:
  - docker

before_install:
  - docker build -t basurohan/docker-project -f Dockerfile.dev .

script:
  - docker run basurohan/docker-project yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-project"
  env: "DockerProject-env"
  bucket_name: "elasticbeanstalk-us-east-2-211121879476"
  bucket_path: "docker-project"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"